name: LocalTunnel Proxy Server

on:
  workflow_dispatch:

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install tinyproxy nodejs npm -y

      - name: Configure Tinyproxy
        run: |
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Port 8888/Port 8080/' /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy

      - name: Install LocalTunnel
        run: |
          sudo npm install -g localtunnel

      - name: Start LocalTunnel Tunnel
        run: |
          nohup lt --port 8080 --subdomain proxy$RANDOM > lt.log 2>&1 &
          sleep 5
          echo "===== LocalTunnel Output Start ====="
          cat lt.log | head -n 20
          echo "===== LocalTunnel Output End ====="
          sleep 300
