name: Ngrok Proxy Server

on:
  workflow_dispatch:

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y tinyproxy curl unzip

      - name: Configure Tinyproxy
        run: |
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Port 8888/Port 8080/' /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy

      - name: Download Ngrok
        run: |
          curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok

      - name: Authenticate Ngrok
        run: |
          ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok TCP Tunnel for Tinyproxy
        run: |
          nohup ./ngrok tcp 8080 > ngrok.log 2>&1 &
          sleep 10
          echo "===== Ngrok Tunnel Info ====="
          curl -s http://127.0.0.1:4040/api/tunnels
          echo "============================="
          sleep 86400
