name: TinyProxy + Localhost.run Tunnel

on:
  workflow_dispatch:

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tinyproxy
      run: |
        sudo apt update
        sudo apt install tinyproxy openssh-client -y
        sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
        sudo sed -i 's/^Port 8888/Port 8080/' /etc/tinyproxy/tinyproxy.conf
        sudo systemctl restart tinyproxy

    - name: Setup SSH key
      run: |
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
        ssh-keyscan -t rsa ssh.localhost.run >> ~/.ssh/known_hosts

    - name: Create Reverse SSH Tunnel (localhost.run)
      run: |
        ssh -R 80:localhost:8080 ssh.localhost.run
