name: Tinyproxy + TryCloudflare

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tinyproxy
      run: |
        sudo apt update
        sudo apt install -y tinyproxy

    - name: Configure Tinyproxy
      run: |
        sudo sed -i 's/^Allow/#Allow/' /etc/tinyproxy/tinyproxy.conf
        echo "Allow 0.0.0.0" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
        sudo sed -i 's/^Port 8888/Port 8888/' /etc/tinyproxy/tinyproxy.conf
        sudo sed -i 's/^Bind 127.0.0.1/#Bind 127.0.0.1/' /etc/tinyproxy/tinyproxy.conf
        sudo systemctl restart tinyproxy

    - name: Download cloudflared (Cloudflare Tunnel)
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod +x cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

    - name: Start Tunnel
      run: |
        nohup cloudflared tunnel --url http://localhost:8888 > tunnel.log 2>&1 &
        sleep 10
        cat tunnel.log | grep -o 'https://.*\.trycloudflare\.com' || echo "Tunnel URL not found."

    - name: Show Tunnel URL
      run: |
        echo "Your Cloudflare Proxy:"
        grep -o 'https://.*\.trycloudflare\.com' tunnel.log || echo "URL not found"
        
