name: Tinyproxy + Cloudflare Tunnel

on:
  workflow_dispatch:
  push:

jobs:
  tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tinyproxy
      run: |
        sudo apt update
        sudo apt install -y tinyproxy curl

    - name: Configure Tinyproxy
      run: |
        sudo sed -i 's/^Port .*/Port 8888/' /etc/tinyproxy/tinyproxy.conf
        sudo sed -i 's/^Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
        echo "DisableViaHeader Yes" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
        echo "ConnectPort 443" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
        echo "ConnectPort 80" | sudo tee -a /etc/tinyproxy/tinyproxy.conf

    - name: Start Tinyproxy
      run: sudo systemctl restart tinyproxy

    - name: Install Cloudflared
      run: |
        curl -s https://pkg.cloudflare.com/cloudflared-stable-linux-amd64.deb -o cloudflared.deb
        sudo dpkg -i cloudflared.deb

    - name: Start Tunnel
      run: |
        nohup cloudflared tunnel --url http://localhost:8888 > tunnel.log 2>&1 &
        sleep 10
        curl -s https://trycloudflare.com > cf.txt || true
        grep -Eo 'https://[-a-z0-9]+\.trycloudflare\.com' cf.txt || echo "Tunnel URL not found"

    - name: Keep Alive
      run: |
        while true; do
          echo "Tunnel active..."
          sleep 300
        done
