name: File Manager with Tunnel

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and install Filebrowser
        run: |
          curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
          chmod +x filebrowser

      - name: Start Filebrowser in background
        run: |
          nohup ./filebrowser -r . -p 8080 > filebrowser.log 2>&1 &

      - name: Wait for Filebrowser to start
        run: sleep 5

      - name: Start Cloudflare tunnel
        run: |
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:8080
          
