name: Cloudflared SOCKS5 Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  cloudflared:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SOCKS5 Proxy (no auth)
        run: |
          sudo apt update
          sudo apt install -y dante-server
          cat <<EOF | sudo tee /etc/danted.conf
logoutput: stderr
internal: 0.0.0.0 port = 1080
external: eth0
method: none
user.privileged: root
user.notprivileged: nobody
client pass {
  from: 0.0.0.0/0 to: 0.0.0.0/0
  log: connect disconnect error
}
pass {
  from: 0.0.0.0/0 to: 0.0.0.0/0
  protocol: tcp udp
}
EOF
          sudo systemctl restart danted

      - name: Download Cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
          chmod +x cloudflared

      - name: Start Cloudflared Tunnel (SOCKS5 on port 1080)
        run: |
          ./cloudflared tunnel --url socks5://localhost:1080 --no-autoupdate > tunnel.log 2>&1 &
          sleep 10
          echo "Cloudflared Tunnel Started"
          cat tunnel.log | grep -o "https://.*trycloudflare.com" || echo "Tunnel URL not found"

