name: Tunnel Session

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: sudo apt update && sudo apt install openssh-client -y

      - name: Start Web Server on Port 8080
        run: |
          mkdir public && echo "Tunnel is working!" > public/index.html
          nohup python3 -m http.server 8080 --directory public > /dev/null 2>&1 &
          echo "Web server running at localhost:8080"

      - name: Start Serveo Tunnel
        run: |
          nohup ssh -o StrictHostKeyChecking=no -R 80:localhost:8080 serveo.net > serveo.log 2>&1 &
          sleep 8
          TUNNEL_URL=$(grep -oP "https://[a-z0-9]+\.serveo.net" serveo.log | head -n 1)
          echo "Tunnel is live at:"
          echo "$TUNNEL_URL"

      - name: Keep Workflow Running
        run: tail -f /dev/null
        
