name: Session Launcher

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cloud Relay
        run: |
          sudo apt update
          sudo apt install openssh-client -y
          ssh -o StrictHostKeyChecking=no -R 80:localhost:8080 serveo.net &
          sleep 5
          echo "Tunnel initiated."
          
