name: Ngrok Proxy Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Install TinyProxy
        run: |
          sudo apt update
          sudo apt install tinyproxy -y
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Port 8888/Port 8080/' /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy
          echo "TinyProxy started on port 8080"

      - name: Download & Configure Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y
          ngrok config add-authtoken 2eotogA5R4KDNhGM3LPPec0uk9D_5JwsdDjfp5mbogqyAUepa

      - name: Start Ngrok TCP Tunnel
        run: |
          nohup ngrok tcp 8080 > ngrok.log 2>&1 &
          sleep 10
          cat ngrok.log | grep -Eo "tcp://[0-9a-zA-Z.:]+" | head -n 1

      - name: Keep Workflow Alive
        run: tail -f /dev/null
        
