name: Session Launcher

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Start Serveo Tunnel and Keep Alive
        run: |
          sudo apt update
          sudo apt install openssh-client -y
          nohup ssh -o StrictHostKeyChecking=no -R 80:localhost:8080 serveo.net > tunnel.log 2>&1 &
          echo "Tunnel started at $(date)"
          echo "Keep session alive..."
          tail -f /dev/null
          
