name: Ngrok SSH Tunnel

on:
  workflow_dispatch:

jobs:
  ssh-ngrok:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH server
      run: |
        sudo apt update
        sudo apt install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo 'root:root' | sudo chpasswd
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh

    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok -y

    - name: Start Ngrok Tunnel
      env:
        NGROK_AUTHTOKEN: 2eotogA5R4KDNhGM3LPPec0uk9D_5JwsdDjfp5mbogqyAUepa
      run: |
        ngrok config add-authtoken $NGROK_AUTHTOKEN
        nohup ngrok tcp 22 --region ap > ngrok.log &
        sleep 10
        cat ngrok.log | grep "tcp://"
        
