name: Minecraft Server 14GB + Ngrok TCP + Auto World Backup

on:
  workflow_dispatch:

jobs:
  minecraft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download Minecraft Server
        run: |
          mkdir -p server
          cd server
          curl -o server.jar https://launcher.mojang.com/v1/objects/e3adc06c47d2ef56cc55f01f2eeb2d0b68413545/server.jar
          echo "eula=true" > eula.txt

      - name: Start Minecraft Server in Background
        run: |
          cd server
          nohup java -Xmx14G -Xms2G -jar server.jar nogui > mc.log 2>&1 &

      - name: Install and Start Ngrok TCP Tunnel for port 25565
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y
          ngrok config add-authtoken 2eotogA5R4KDNhGM3LPPec0uk9D_5JwsdDjfp5mbogqyAUepa
          nohup ngrok tcp 25565 > ngrok.log 2>&1 &
          sleep 8
          echo "==== NGROK PUBLIC ADDRESS ===="
          cat ngrok.log | grep -o "tcp://[0-9a-zA-Z\.\:]*"

      - name: Keep Server Running
        run: sleep 21500

      - name: Auto Backup Minecraft World
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull
          git add server/world || true
          git commit -m "Auto-backup world after run" || echo "No changes"
          git push || echo "No push access"
          
