name: WireGuard with Ngrok Tunnel

on:
  workflow_dispatch:

jobs:
  wireguard-ngrok:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install wireguard -y
          mkdir -p wg

      - name: Generate WireGuard Keys
        run: |
          cd wg
          umask 077
          wg genkey | tee privatekey | wg pubkey > publickey

      - name: Create WireGuard Server Config
        run: |
          cd wg
          PRIV_KEY=$(cat privatekey)
          echo "[Interface]" > wg0.conf
          echo "Address = 10.0.0.1/24" >> wg0.conf
          echo "PrivateKey = $PRIV_KEY" >> wg0.conf
          echo "ListenPort = 51820" >> wg0.conf

      - name: Show WireGuard Public Key
        run: |
          echo "===== WireGuard Server Public Key ====="
          cat wg/publickey

      - name: Start WireGuard
        run: sudo wg-quick up wg/wg0.conf

      - name: Install Ngrok via APT
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ngrok -y

      - name: Add Ngrok Auth Token
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok TCP Tunnel on port 51820
        run: |
          ngrok tcp 51820 &

      - name: Keep Alive 24/7
        run: sleep infinity
