name: WireGuard + Loophole

on:
  workflow_dispatch:

jobs:
  loophole:
    runs-on: ubuntu-latest

    steps:
    - name: Set up directories
      run: |
        mkdir -p wg
        cd wg
        umask 077

    - name: Install WireGuard
      run: |
        sudo apt update
        sudo apt install wireguard -y

    - name: Generate WireGuard Keys
      run: |
        cd wg
        wg genkey | tee privatekey | wg pubkey > publickey

    - name: Create WireGuard Config
      run: |
        cd wg
        PRIV_KEY=$(cat privatekey)
        cat <<EOF > wg0.conf
[Interface]
Address = 10.0.0.1/24
PrivateKey = $PRIV_KEY
ListenPort = 51820
EOF
        echo "Public key for client config:" && cat publickey

    - name: Start WireGuard
      run: |
        sudo wg-quick up wg/wg0.conf

    - name: Download Loophole
      run: |
        curl -Lo loophole.tar.gz https://github.com/loophole/cli/releases/download/1.0.0-beta.15/loophole-cli_1.0.0-beta.15_linux_64bit.tar.gz
        tar -xzf loophole.tar.gz
        chmod +x loophole

    - name: Start Loophole TCP Tunnel
      run: |
        ./loophole tunnel tcp --port 51820 --hostname wireguard-$(date +%s) &
        sleep 10
        echo "Tunnel running. Client should connect to this Loophole public TCP endpoint."

    - name: Show WireGuard and Tunnel Info
      run: |
        echo "========== PUBLIC KEY =========="
        cat wg/publickey
        echo "========== SERVER CONFIG =========="
        cat wg/wg0.conf
