name: Ubuntu XFCE4 + noVNC + Ngrok

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-24.04

    steps:
    - name: Update & Install Packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xfce4 xfce4-goodies x11vnc xvfb \
          websockify novnc net-tools wget curl unzip \
          firefox chromium-browser

    - name: Start VNC Server
      run: |
        mkdir -p ~/.vnc
        x11vnc -storepasswd "github" ~/.vnc/passwd
        Xvfb :1 -screen 0 1366x768x16 &
        export DISPLAY=:1
        startxfce4 &

    - name: Start noVNC
      run: |
        nohup websockify --web=/usr/share/novnc 6080 localhost:5900 > novnc.log 2>&1 &

    - name: Download ngrok
      run: |
        wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok.zip
        chmod +x ./ngrok

    - name: Start Ngrok Tunnel
      run: |
        # यहाँ पर अपना ngrok authtoken डालना मत भूलना
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok http 6080 > ngrok.log 2>&1 &

    - name: Show Tunnel URL
      run: |
        sleep 5
        curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Keep Alive
      run: |
        echo "Press Ctrl+C to stop"
        while true; do sleep 30; done
