name: SSH over Ngrok (Password Login)

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install SSH & Ngrok
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server curl unzip jq
          sudo mkdir -p /run/sshd

          # Create user skyt with password skyt
          echo "Creating user skyt..."
          sudo useradd -m -s /bin/bash skyt || true
          echo "skyt:skyt" | sudo chpasswd
          echo 'skyt ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/90-skyt

          # Enable password login
          sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config

          sudo /usr/sbin/sshd

          # Add ngrok official apt repo + install
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

      - name: Authenticate ngrok
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          ngrok config add-authtoken "$NGROK_AUTHTOKEN"

      - name: Start ngrok TCP tunnel
        run: |
          nohup ngrok tcp 22 --log=stdout > ngrok.log 2>&1 &
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
          cat tunnels.json

      - name: Show connection info
        run: |
          HOST=$(jq -r '.tunnels[0].public_url' tunnels.json | sed 's#tcp://##' | cut -d: -f1)
          PORT=$(jq -r '.tunnels[0].public_url' tunnels.json | sed 's#tcp://##' | cut -d: -f2)
          echo "====================================="
          echo " Connect with:"
          echo "   ssh -p $PORT skyt@$HOST"
          echo " Password: skyt"
          echo "====================================="

      - name: Keep alive
        run: |
          while true; do sleep 60; done
