name: SSHX 24x7

on:
  workflow_dispatch:    # manually start karne ke liye
  schedule:
    - cron: "0 */12 * * *"   # har 12 ghante me auto restart

jobs:
  sshx:
    runs-on: ubuntu-latest
    timeout-minutes: 4320   # max 72h

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Run SSHX
        run: |
          echo "=== Installing SSHX ==="
          curl -sSf https://sshx.io/get | sh -s run &
          sleep 5
          echo "=== SSHX Started, check above logs for your connection URL ==="

      - name: Keep Alive
        run: |
          echo "Keeping workflow alive..."
          while true; do
            echo "[$(date)] Still alive..."
            sleep 300
          done
