name: Teleport TCP Tunnel with Tinyproxy

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tinyproxy + Neofetch
        run: |
          sudo apt update
          sudo apt install -y tinyproxy neofetch curl

          # Tinyproxy config
          sudo sed -i 's/^Port .*/Port 8080/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Allow.*/#Allow/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Bind.*/#Bind/' /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy

          neofetch || true

      - name: Download and Start Teleport Tunnel
        run: |
          curl -L -o teleport https://github.com/tryteleport/teleport/releases/latest/download/teleport-linux-x64
          chmod +x teleport
          ./teleport tcp --port 8080 > tunnel.txt 2>&1 &
          sleep 10
          cat tunnel.txt | grep teleport.sh || true

      - name: Keep Tunnel Alive
        run: |
          while sleep 60; do echo "Still running..."; done
          
