name: Tinyproxy + Cloudflare HTTP Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y tinyproxy neofetch git build-essential cmake

          # Install fastfetch
          git clone https://github.com/fastfetch-cli/fastfetch.git
          cd fastfetch
          mkdir build && cd build
          cmake ..
          make
          sudo make install
          
          echo "=== Fastfetch ==="
          fastfetch || true
          echo "=== Neofetch ==="
          neofetch || true

      - name: Configure Tinyproxy
        run: |
          sudo sed -i 's/^Allow.*/#Allow/g' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/g' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Port .*/Port 8080/g' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Bind.*/#Bind/g' /etc/tinyproxy/tinyproxy.conf
          echo "MaxClients 100" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          echo "MaxRequestsPerChild 0" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy

      - name: Download & Start Cloudflare Tunnel
        run: |
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:8080 --no-autoupdate
          
