name: Net Update Service

on:
  workflow_dispatch:

jobs:
  serveo-tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tinyproxy & Neofetch
        run: |
          sudo apt update
          sudo apt install -y tinyproxy neofetch openssh-client

          sudo sed -i 's/^Port .*/Port 8080/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Allow.*/#Allow/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Bind.*/#Bind/' /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy
          echo "=== Neofetch ==="
          neofetch || true

      - name: Start Serveo Tunnel
        run: |
          echo "Starting Serveo tunnel on port 8080..."
          ssh -o StrictHostKeyChecking=no -R netservice123:80:localhost:8080 serveo.net > serveo.log 2>&1 &
          sleep 10
          echo "=== Serveo Tunnel Output ==="
          cat serveo.log || echo "Tunnel error"
          echo "=== Serveo Public Link ==="
          echo "https://netservice123.serveo.net"

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Tunnel running..."; done
          
