name: Teleport TCP Tunnel with Tinyproxy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  teleport:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tinyproxy + Neofetch
        run: |
          sudo apt update
          sudo apt install -y tinyproxy neofetch curl

          # Configure Tinyproxy on port 8080, allow all
          sudo sed -i 's/^Port .*/Port 8080/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Allow.*/#Allow/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Bind.*/#Bind/' /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy

          neofetch || true

      - name: Download and Start Teleport TCP Tunnel
        run: |
          curl -s https://teleport.sh/install.sh | bash
          teleport tcp --port 8080 > tunnel.txt 2>&1 &
          sleep 10
          cat tunnel.txt | grep -i "teleport.sh" || true

      - name: Keep Workflow Alive
        run: |
          while sleep 60; do echo "Still tunneling via Teleport..."; done
          
