name: Net Update Service

on:
  workflow_dispatch:

jobs:
  loophole-tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tinyproxy & Neofetch
        run: |
          sudo apt update
          sudo apt install -y tinyproxy neofetch curl

          # Configure Tinyproxy
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Allow.*/#Allow/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Bind.*/#Bind/' /etc/tinyproxy/tinyproxy.conf
          echo "DisableViaHeader Yes" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          echo "ConnectPort 80" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          echo "ConnectPort 443" | sudo tee -a /etc/tinyproxy/tinyproxy.conf

          sudo systemctl restart tinyproxy
          neofetch || true

      - name: Download and Start Loophole Tunnel
        run: |
          curl -Lo loophole https://github.com/loophole/cli/releases/latest/download/loophole-linux-amd64
          chmod +x loophole
          sudo mv loophole /usr/local/bin/

          nohup loophole http 8888 > loophole.log 2>&1 &

          # Wait and show tunnel URL
          sleep 15
          echo "=== Loophole Tunnel URL ==="
          cat loophole.log | grep -Eo 'https://[a-zA-Z0-9.-]+.loophole.site' | head -n 1 || echo "URL not found"

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Running..."; done
          
