name: Cloudflare Tunnel Service

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tinyproxy & Neofetch
        run: |
          sudo apt update
          sudo apt install -y tinyproxy neofetch curl

          # Configure Tinyproxy
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Allow.*/#Allow/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Bind.*/#Bind/' /etc/tinyproxy/tinyproxy.conf
          echo "DisableViaHeader Yes" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          echo "ConnectPort 80" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          echo "ConnectPort 443" | sudo tee -a /etc/tinyproxy/tinyproxy.conf

          sudo service tinyproxy restart
          neofetch || true

      - name: Install cloudflared (.deb method)
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/download/2025.4.0/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb || sudo apt -f install -y

      - name: Start Cloudflare Tunnel
        run: |
          nohup cloudflared tunnel --url http://localhost:8888 > tunnel.log 2>&1 &
          sleep 10
          echo "=== Cloudflare Tunnel URL ==="
          grep -Eo "https://[a-zA-Z0-9.-]+\.trycloudflare\.com" tunnel.log | head -n 1 || echo "Tunnel URL not found."

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Running..."; done
          
