name: HAProxy with Ngrok Tunnel

on:
  workflow_dispatch:

jobs:
  haproxy-ngrok:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install HAProxy, Ngrok, and Dependencies
        run: |
          sudo apt update
          sudo apt install -y haproxy curl jq

      - name: Start Ngrok Tunnel (TCP)
        run: |
          ngrok tcp 8080 > ngrok.log 2>&1 &
          sleep 5
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
          echo "Ngrok Tunnel URL: $NGROK_URL"
          echo $NGROK_URL > ngrok_url.txt

      - name: Configure HAProxy
        run: |
          NGROK_URL=$(cat ngrok_url.txt | sed 's/tcp:\/\//'/)
          echo "Configuring HAProxy with Ngrok URL: $NGROK_URL"

          # Backup original haproxy.cfg
          sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

          # Update HAProxy config to forward to Ngrok
          sudo bash -c 'echo "frontend http-in
          bind *:8080
          default_backend http-proxy
          backend http-proxy
          server proxy1 $NGROK_URL  # Forward to the Ngrok TCP tunnel URL" > /etc/haproxy/haproxy.cfg'

          # Restart HAProxy to apply the changes
          sudo service haproxy restart

      - name: Check HAProxy Service Status
        run: |
          sudo systemctl status haproxy.service

      - name: Test Tunnel with Curl
        run: |
          curl -x http://localhost:8080 http://google.com -L
          
      - name: Keep Alive
        run: |
          while sleep 60; do echo "Running..."; done
