name: Ngrok + HAProxy + Python HTTP Tunnel

on:
  workflow_dispatch:

jobs:
  http-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python HTTP Server
        run: |
          sudo apt update
          sudo apt install -y python3 haproxy curl jq

          mkdir -p ~/http-server
          echo '<h1>HAProxy + Ngrok + Python</h1>' > ~/http-server/index.html

          # Start Python HTTP server in background
          nohup python3 -m http.server 8080 --directory ~/http-server &
          sleep 3

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y

      - name: Start Ngrok Tunnel
        env:
          NGROK_AUTHTOKEN: 2eotogA5R4KDNhGM3LPPec0uk9D_5JwsdDjfp5mbogqyAUepa
        run: |
          ngrok config add-authtoken "$NGROK_AUTHTOKEN"
          nohup ngrok tcp 80 > ngrok.log 2>&1 &
          sleep 5

          # Extract Ngrok URL
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
          if [ -z "$NGROK_URL" ]; then
            echo "ERROR: Ngrok URL not found"
            cat ngrok.log
            exit 1
          fi

          echo "Ngrok Tunnel: $NGROK_URL"
          echo $NGROK_URL | sed 's/tcp:\/\///' > ngrok_url.txt

      - name: Configure HAProxy with Python Server
        run: |
          NGROK_HOST_PORT=$(cat ngrok_url.txt)

          sudo bash -c "cat > /etc/haproxy/haproxy.cfg" <<EOF
          global
              daemon
              maxconn 256

          defaults
              mode http
              timeout connect 5000ms
              timeout client 50000ms
              timeout server 50000ms

          frontend http-in
              bind *:80
              default_backend python-server

          backend python-server
              server localserver 127.0.0.1:8080
          EOF

          sudo service haproxy restart

      - name: Test Tunnel
        run: |
          curl -x http://localhost:80 http://localhost -L -m 10 -v || echo "Test failed"

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Running..."; done
          
