name: Setup Ngrok Tunnel

on:
  workflow_dispatch:  # Allows manual trigger of the workflow from GitHub UI

jobs:
  setup-ngrok:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl jq

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y

      - name: Configure Ngrok Authtoken
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
        
      - name: Start Ngrok TCP Tunnel
        run: |
          nohup ngrok tcp 8080 > ngrok.log 2>&1 &
          sleep 5

      - name: Fetch Ngrok URL
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
          echo "Ngrok Tunnel URL: $NGROK_URL"
          echo $NGROK_URL > ngrok_url.txt

      - name: Check Ngrok URL format
        run: |
          NGROK_URL=$(cat ngrok_url.txt)
          echo "DEBUG: Ngrok URL is: $NGROK_URL"
          if [[ ! "$NGROK_URL" =~ ^[a-zA-Z0-9.-]+:[0-9]+$ ]]; then
            echo "ERROR: Invalid Ngrok URL format!"
            exit 1
          fi

      - name: Test Tunnel to Google.com via Proxy
        run: |
          echo "Testing Proxy Tunnel..."
          curl -x http://localhost:8080 http://google.com -L -m 10 -v || echo "Test failed"

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Running..."; done
          
