name: Setup Ngrok Tunnel with HAProxy

on:
  workflow_dispatch:

jobs:
  setup-tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq curl haproxy snapd
          sudo snap install ngrok --classic

      - name: Add Ngrok Authtoken
        run: |
          ngrok config add-authtoken $NGROK_AUTHTOKEN
          echo "Ngrok Authtoken added successfully."

      - name: Start Ngrok TCP Tunnel
        run: |
          ngrok tcp 8080 > ngrok.log 2>&1 &
          sleep 5
          
          # Fetch the Ngrok URL (TCP format)
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
          
          # Check if Ngrok URL is fetched correctly
          if [ -z "$NGROK_URL" ]; then
            echo "ERROR: Ngrok URL could not be retrieved."
            cat ngrok.log
            exit 1
          fi
          
          echo "Ngrok Tunnel URL: $NGROK_URL"
          
          # Remove the 'tcp://' prefix for HAProxy use
          CLEAN_NGROK_URL=$(echo $NGROK_URL | sed 's/tcp:\/\///')
          echo $CLEAN_NGROK_URL > ngrok_url.txt

      - name: Check Ngrok URL format
        run: |
          NGROK_URL=$(cat ngrok_url.txt)
          echo "DEBUG: Ngrok URL is: $NGROK_URL"
          
          # Remove the 'tcp://' prefix for validation
          CLEAN_NGROK_URL=$(echo $NGROK_URL | sed 's/tcp:\/\///')
          
          # Validate the Ngrok URL format (expecting 'host:port')
          if [[ ! "$CLEAN_NGROK_URL" =~ ^[a-zA-Z0-9.-]+:[0-9]+$ ]]; then
            echo "ERROR: Invalid Ngrok URL format!"
            exit 1
          fi

      - name: Configure HAProxy with Ngrok URL
        run: |
          NGROK_URL=$(cat ngrok_url.txt)
          echo "Configuring HAProxy with Ngrok URL: $NGROK_URL"
          
          # Backup original haproxy.cfg
          sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
          
          # Update HAProxy config to forward to Ngrok
          sudo bash -c "echo 'frontend http-in
          bind *:8080
          default_backend http-proxy
          backend http-proxy
          server proxy1 $NGROK_URL' > /etc/haproxy/haproxy.cfg"
          
          # Restart HAProxy to apply the changes
          sudo service haproxy restart

      - name: Test Tunnel to Google
        run: |
          curl -x http://localhost:8080 http://google.com -L -m 10 -v || echo "Test failed"

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Running..."; done
