name: Configure HAProxy with Ngrok Tunnel

on:
  workflow_dispatch:

jobs:
  haproxy-ngrok-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install dependencies (HAProxy, Ngrok, jq)
        run: |
          sudo apt update
          sudo apt install -y haproxy curl jq

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y

      - name: Configure Ngrok Authtoken
        run: |
          ngrok config add-authtoken 2eotogA5R4KDNhGM3LPPec0uk9D_5JwsdDjfp5mbogqyAUepa
          
      - name: Start Ngrok TCP Tunnel
        run: |
          nohup ngrok tcp 8080 > ngrok.log 2>&1 &
          sleep 5

      - name: Fetch Ngrok TCP Tunnel URL
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
          
          # Check if Ngrok URL is fetched correctly
          if [ -z "$NGROK_URL" ]; then
            echo "ERROR: Ngrok URL could not be retrieved."
            cat ngrok.log
            exit 1
          fi

          echo "Ngrok Tunnel URL: $NGROK_URL"
          
          # Remove 'tcp://' part to use the proper format for HAProxy
          NGROK_URL=$(echo $NGROK_URL | sed 's/tcp:\/\///')
          echo $NGROK_URL > ngrok_url.txt

      - name: Backup Original HAProxy Config
        run: |
          sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

      - name: Update HAProxy Config with Ngrok URL
        run: |
          NGROK_URL=$(cat ngrok_url.txt)
          echo "Configuring HAProxy with Ngrok URL: $NGROK_URL"
          
          # Update HAProxy config to forward to Ngrok
          sudo bash -c "echo 'frontend http-in
          bind *:8080
          default_backend http-proxy
          backend http-proxy
          server proxy1 $NGROK_URL' > /etc/haproxy/haproxy.cfg"
          
      - name: Restart HAProxy Service
        run: |
          sudo service haproxy restart

      - name: Check HAProxy Service Status
        run: |
          sudo systemctl status haproxy.service

      - name: Test HAProxy Forwarding via Curl
        run: |
          curl -x http://localhost:8080 http://google.com -L

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Running..."; done
          
