name: Cloudflare Proxy Tunnel

on:
  workflow_dispatch:

jobs:
  cf-tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tinyproxy & Neofetch
        run: |
          sudo apt update
          sudo apt install -y tinyproxy neofetch curl

          # Configure Tinyproxy
          sudo sed -i 's/^#Allow 127.0.0.1/Allow 0.0.0.0/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Allow.*/#Allow/' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^Bind.*/#Bind/' /etc/tinyproxy/tinyproxy.conf
          echo "DisableViaHeader Yes" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          echo "ConnectPort 80" | sudo tee -a /etc/tinyproxy/tinyproxy.conf
          echo "ConnectPort 443" | sudo tee -a /etc/tinyproxy/tinyproxy.conf

          sudo service tinyproxy restart
          neofetch || true

      - name: Download Cloudflare Tunnel Binary
        run: |
          curl -fsSL https://trycloudflare.com -o cf
          chmod +x cf

      - name: Start Cloudflare Tunnel
        run: |
          nohup ./cf tunnel --url http://localhost:8888 > tunnel.log 2>&1 &
          sleep 15
          echo "=== Cloudflare Tunnel URL ==="
          grep -Eo "https://[a-zA-Z0-9.-]+\.trycloudflare\.com" tunnel.log | head -n 1 || echo "URL not found"

      - name: Keep Alive
        run: |
          while sleep 60; do echo "Tunnel running..."; done
          
